# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(893, 627)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 470, 311, 111))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.queryImgPath = QtWidgets.QTextEdit(self.frame)
        self.queryImgPath.setGeometry(QtCore.QRect(10, 20, 191, 31))
        self.queryImgPath.setObjectName("queryImgPath")
        self.importImgButton = QtWidgets.QPushButton(self.frame)
        self.importImgButton.setGeometry(QtCore.QRect(220, 30, 75, 23))
        self.importImgButton.setObjectName("importImgButton")
        self.searchButton = QtWidgets.QPushButton(self.frame)
        self.searchButton.setGeometry(QtCore.QRect(90, 70, 111, 31))
        self.searchButton.setObjectName("searchButton")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(10, 120, 311, 301))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.queryImg = QtWidgets.QLabel(self.frame_2)
        self.queryImg.setGeometry(QtCore.QRect(40, 35, 221, 221))
        self.queryImg.setText("")
        self.queryImg.setAlignment(QtCore.Qt.AlignCenter)
        self.queryImg.setObjectName("queryImg")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(350, 120, 491, 491))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 471, 470))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.result1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.result1.setText("")
        self.result1.setAlignment(QtCore.Qt.AlignCenter)
        self.result1.setObjectName("result1")
        self.gridLayout.addWidget(self.result1, 0, 0, 1, 1)
        self.result2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.result2.setText("")
        self.result2.setAlignment(QtCore.Qt.AlignCenter)
        self.result2.setObjectName("result2")
        self.gridLayout.addWidget(self.result2, 0, 1, 1, 1)
        self.result3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.result3.setText("")
        self.result3.setAlignment(QtCore.Qt.AlignCenter)
        self.result3.setObjectName("result3")
        self.gridLayout.addWidget(self.result3, 0, 2, 1, 1)
        self.result4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.result4.setText("")
        self.result4.setAlignment(QtCore.Qt.AlignCenter)
        self.result4.setObjectName("result4")
        self.gridLayout.addWidget(self.result4, 0, 3, 1, 1)
        self.result5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.result5.setText("")
        self.result5.setAlignment(QtCore.Qt.AlignCenter)
        self.result5.setObjectName("result5")
        self.gridLayout.addWidget(self.result5, 0, 4, 1, 1)
        self.result6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.result6.setText("")
        self.result6.setAlignment(QtCore.Qt.AlignCenter)
        self.result6.setObjectName("result6")
        self.gridLayout.addWidget(self.result6, 1, 0, 1, 1)
        self.result7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.result7.setText("")
        self.result7.setAlignment(QtCore.Qt.AlignCenter)
        self.result7.setObjectName("result7")
        self.gridLayout.addWidget(self.result7, 1, 1, 1, 1)
        self.result8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.result8.setText("")
        self.result8.setAlignment(QtCore.Qt.AlignCenter)
        self.result8.setObjectName("result8")
        self.gridLayout.addWidget(self.result8, 1, 2, 1, 1)
        self.result9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.result9.setText("")
        self.result9.setAlignment(QtCore.Qt.AlignCenter)
        self.result9.setObjectName("result9")
        self.gridLayout.addWidget(self.result9, 1, 3, 1, 1)
        self.result10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.result10.setText("")
        self.result10.setAlignment(QtCore.Qt.AlignCenter)
        self.result10.setObjectName("result10")
        self.gridLayout.addWidget(self.result10, 1, 4, 1, 1)
        self.result15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.result15.setText("")
        self.result15.setAlignment(QtCore.Qt.AlignCenter)
        self.result15.setObjectName("result15")
        self.gridLayout.addWidget(self.result15, 8, 4, 1, 1)
        self.result14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.result14.setText("")
        self.result14.setAlignment(QtCore.Qt.AlignCenter)
        self.result14.setObjectName("result14")
        self.gridLayout.addWidget(self.result14, 8, 3, 1, 1)
        self.result13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.result13.setText("")
        self.result13.setAlignment(QtCore.Qt.AlignCenter)
        self.result13.setObjectName("result13")
        self.gridLayout.addWidget(self.result13, 8, 2, 1, 1)
        self.result12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.result12.setText("")
        self.result12.setAlignment(QtCore.Qt.AlignCenter)
        self.result12.setObjectName("result12")
        self.gridLayout.addWidget(self.result12, 8, 1, 1, 1)
        self.result11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.result11.setText("")
        self.result11.setAlignment(QtCore.Qt.AlignCenter)
        self.result11.setObjectName("result11")
        self.gridLayout.addWidget(self.result11, 8, 0, 1, 1)
        self.importQueryButton = QtWidgets.QPushButton(Form)
        self.importQueryButton.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.importQueryButton.setObjectName("importQueryButton")
        self.importReferenceButton = QtWidgets.QPushButton(Form)
        self.importReferenceButton.setGeometry(QtCore.QRect(10, 60, 111, 31))
        self.importReferenceButton.setObjectName("importReferenceButton")
        self.queryPath = QtWidgets.QTextEdit(Form)
        self.queryPath.setGeometry(QtCore.QRect(133, 10, 191, 31))
        self.queryPath.setObjectName("queryPath")
        self.referencePath = QtWidgets.QTextEdit(Form)
        self.referencePath.setGeometry(QtCore.QRect(130, 60, 191, 31))
        self.referencePath.setObjectName("referencePath")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(460, 10, 118, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.resultButton = QtWidgets.QPushButton(Form)
        self.resultButton.setGeometry(QtCore.QRect(354, 10, 81, 31))
        self.resultButton.setObjectName("resultButton")

        self.retranslateUi(Form)
        self.importImgButton.clicked.connect(Form.openQueryImg)
        self.searchButton.clicked.connect(Form.reid)
        self.resultButton.clicked.connect(Form.reidAll)
        self.importQueryButton.clicked.connect(Form.importQuDir)
        self.importReferenceButton.clicked.connect(Form.importReDir)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.importImgButton.setText(_translate("Form", "打开图片"))
        self.searchButton.setText(_translate("Form", "检索"))
        self.importQueryButton.setText(_translate("Form", "导入query图库"))
        self.importReferenceButton.setText(_translate("Form", "导入reference图库"))
        self.resultButton.setText(_translate("Form", "导出xml"))

